Add Error Checking for non-matching UDID
mdmdirector/mdmdirector pull request #79
Opened 2021-07-27 23:29 UTC by gavinelder

2021-07-27 23:49 UTC, gavinelder commented on director/profile.go
> +		errorMSG := fmt.Sprintf("Device Profiles returned no records found for device UDID = %s.\n", vars["udid"])
LGTM correctly caught this as an XSS risk, although gated I will remove the var.

2022-01-19 23:32 UTC, grahamgilbert commented
I feel that this should be a warning rather than an error in the log (I have no desire to be paged if someone hits this), but other than that lgtm

2022-01-21 09:31 UTC, gavinelder commented
> I feel that this should be a warning rather than an error in the log (I have no desire to be paged if someone hits this), but other than that lgtm

Np will go back through this and make changes

2022-05-24 15:39 UTC, grahamgilbert approved these changes

2022-05-24 15:41 UTC, grahamgilbert requested changes
As discussed, let's log to a warning here.

2023-02-16 15:36 UTC, closed without merging